### ISSUE TITLE
Activity com.razorpay.CheckoutActivity has leaked IntentReceiver

### ISSUE THREAD

**Issue by sumit-subedi** [razorpay/razorpay-java#126] opened 2021-07-17 18:05 UTC
I am trying to integrate razorpay on android and I am facing a issue that has already been raised but solutions are not working for me.
` private void makepayment() {
        Checkout checkout = new Checkout();
        checkout.setKeyID("rzp_test_Gj9ClQXvE7sb9p");
        checkout.setImage(R.drawable.logo);

        /**
         * Reference to current activity
         */
        final Activity activity = this;

        /**
         * Pass your payment options to the Razorpay Checkout as a JSONObject
         */
        try {
            JSONObject options = new JSONObject();

            options.put("name", "test Payment");
            options.put("description", "Reference No. #123456");
            options.put("image", "https://s3.amazonaws.com/rzp-mobile/images/rzp.png");
           //options.put("order_id", "order_DBJOWzybf0sJbb");//from response of step 3.
            options.put("theme.color", "#3399cc");
            options.put("currency", "INR");
            options.put("amount", "50000");//pass amount in currency subunits
            options.put("prefill.email", "gaurav.kumar@example.com");
            options.put("prefill.contact","xxxxxxxxxx");
            JSONObject retryObj = new JSONObject();
            retryObj.put("enabled", true);
            retryObj.put("max_count", 4);
            options.put("retry", retryObj);

            checkout.open(activity, options);

        } catch(Exception e) {
            Log.e("TAG", "Error in starting Razorpay Checkout", e);
        }
    }
    public void onPaymentSuccess(String s, PaymentData paymentData) {
        text.setText("Payment Sucessfull" + s);

    }

    @Override
    public void onPaymentError(int i, String s, PaymentData paymentData) {
        text.setText("Payment Failed because" + s);
    }`

What happens here is the payment succeeds. It comes through on dashboard and the textview is also saying payment successfull. But it throws an error. I was looking to send the information to backend but I cannot do because of the error. This is the entire error
    `2021-07-17 23:27:13.161 5904-5904/com.example.loginapplication E/com.razorpay.checkout: Webview JS Error: Uncaught 
  ReferenceError: otpPermissionCallback is not defined
  2021-07-17 23:27:13.163 5904-5904/com.example.loginapplication I/chromium: [INFO:CONSOLE(1)] "Uncaught 
  ReferenceError: otpPermissionCallback is not defined", source: 
 https://api.razorpay.com/v1/payments/pay_Ha5XW7H1wenZ51/callback/5dbd94043815b9a9fbee2b874e548d5adb1c0268/rzp_t 
 est_Gj9ClQXvE7sb9p?status=authorized&token_recurring_status=rejected&language_code=en (1)
  2021-07-17 23:27:13.164 5904-5904/com.example.loginapplication E/ActivityThread: Activity com.razorpay.CheckoutActivity 
 has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@eb52ce5 that was originally registered here. Are you missing a 
 call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver 
  com.razorpay.AutoReadOtpHelper@eb52ce5 that was originally registered here. Are you missing a call to 
  unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1159)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:946)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1330)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1310)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1304)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:586)
        at com.razorpay.CheckoutPresenterImpl.onSubmit(CheckoutPresenterImpl.java:958)
        at com.razorpay.CheckoutBridge$10.secure(CheckoutBridge.java:158)
        at com.razorpay.CheckoutPresenterImpl.executeWebViewCallback(CheckoutPresenterImpl.java:1257)
        at com.razorpay.CheckoutPresenterImpl.access$700(CheckoutPresenterImpl.java:49)
        at com.razorpay.CheckoutPresenterImpl$17.run(CheckoutPresenterImpl.java:1243)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)`

How can I solve my issue?

P.S I am using latest version of sdk 1.6.10 .

**Comment by Puneet1796** [comment] 2022-01-27 17:37
Duplicate of https://github.com/razorpay/razorpay-java/issues/128

**Comment by ankitdas13** [comment] 2022-10-12 04:49
@sumit-subedi Apologise for the long delay. Could you please let us know if the issue was resolved? 

If some are facing this same issue you can create issue in this [repo](https://github.com/razorpay/razorpay-android) or report this on the [support portal](https://razorpay.com/support/).

**Comment by ankitdas13** [comment] 2022-11-02 07:44
@sumit-subedi Closing this issue, It has already been fixed https://github.com/razorpay/razorpay-java/issues/134 . Please update to the most recent version to resolve this issue also the issue is not related to this repo . If the issue still persists after upgrading could you please create a new issue in this [repo](https://github.com/razorpay/razorpay-android)

**Closed by ankitdas13** 2022-11-02 07:44 UTC
