### ISSUE TITLE
Webhook use 'GET' method

### ISSUE THREAD

**Issue by helloliu01** [razorpay/razorpay-java#176] opened 2022-03-31 13:12 UTC
Dear Team,
I have a problem when I use the webhook. https://razorpay.com/docs/webhooks/ this document says that you will send an HTTP POST payload in JSON to the webhook's configured URL. I provide a POST interface in my spring boot application but when I get the webhook request I get an error "javax.servlet.error.message=Request method 'GET' not supported". I turn the POST interface to a GET interface then I can get the request but I can not get the payload. Can you help me solve it.

**Comment by ankitdas13** [comment] 2022-10-06 04:45
@helloliu01 Apologize for the long delay. Could you please let us know if the issue is resolved ?

**Comment by ankitdas13** [comment] 2022-12-02 06:53
@helloliu01 could you please confirm us ?

**Comment by ankitdas13** [comment] 2022-12-22 07:36
Closing this issue for now due to not getting any response. if anyone getting the same issue then please check this [webhook doc](https://razorpay.com/docs/webhooks/validate-test#validate-webhooks).

**Closed by ankitdas13** 2022-12-22 07:36 UTC
Labels: awaiting response
