### ISSUE TITLE
Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@ba8c433 that was originally registered here. Are you missing a call to unregisterReceiver()?

### ISSUE THREAD

**Issue by tanishq14developer** [razorpay/razorpay-java#134] opened 2021-10-06 15:09 UTC
please help unable to make payement

**Comment by Puneet1796** [comment] 2022-01-27 17:36
Duplicate of https://github.com/razorpay/razorpay-java/issues/128

**Comment by ankitdas13** [comment] 2022-10-11 11:51
@tanishq14developer could you please let us know if this issue has been fixed? also i dont think so its from sdk side.

**Comment by tanishq14developer** [comment] 2022-10-11 15:16
@ankitdas13 in updated sdk it has been resolved

**Closed** 2022-10-11 15:16 UTC

**Comment by dhavalpatel666** [comment] 2022-11-30 11:55
I am using 'com.razorpay:checkout:1.6.26' in my android dependencies.

While running the payment scenario for my app, I am getting the below error go to razorpay page

java.lang.NoSuchFieldError: No static field NO_OPTIONS of type Lcom/google/android/gms/common/api/Api$ApiOptions$NoOptions; in class Lcom/google/android/gms/common/api/Api$ApiOptions; or its superclasses (declaration of 'com.google.android.gms.common.api.Api$ApiOptions' appears in /data/app/com.smaple-suaPyGsU26tVlh7gKARYpQ==/base.apk!classes2.dex)
        at com.google.android.gms.auth.api.phone.SmsRetrieverClient.<init>(com.google.android.gms:play-services-auth-api-phone@@17.5.1:1)
        at com.google.android.gms.internal.auth-api-phone.zzab.<init>(com.google.android.gms:play-services-auth-api-phone@@17.5.1:1)
        at com.google.android.gms.auth.api.phone.SmsRetriever.getClient(com.google.android.gms:play-services-auth-api-phone@@17.5.1:1)
        at com.razorpay.CheckoutPresenterImpl.onLoad(CheckoutPresenterImpl.java:874)
        at com.razorpay.J$_0_.secure(CheckoutBridge.java:27)
        at com.razorpay.CheckoutPresenterImpl.executeWebViewCallback(CheckoutPresenterImpl.java:1370)
        at com.razorpay.CheckoutPresenterImpl.access$700(CheckoutPresenterImpl.java:55)
        at com.razorpay.b$_f_.run(CheckoutPresenterImpl.java:1355)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
